# frigate-final.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-cache
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-database
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config-data
  namespace: frigate
data:
  config.yml: |
    mqtt:
      host: mqtt-mosquitto.mqtt.svc.cluster.local
      port: 1883
      user: mqttuser
      password: mqttpass
      topic_prefix: frigate
      client_id: frigate

    database:
      path: /media/frigate/db/frigate.db

    birdseye:
      enabled: true
      width: 1920
      height: 1080
      quality: 8
      mode: continuous

    cameras:
      front_door:
        ffmpeg:
          inputs:
            - path: rtsp://admin:password@192.168.1.200/Streaming/Channels/101
              roles:
                - detect
                - rtmp
        detect:
          width: 1920
          height: 1080
          fps: 5
        objects:
          track:
            - person
            - car
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
  labels:
    app.kubernetes.io/name: frigate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
    spec:
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:0.16.2
        ports:
        - containerPort: 5000
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - name: config
          mountPath: /config
        - name: cache
          mountPath: /tmp/cache
        - name: database
          mountPath: /media/frigate/db
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
      volumes:
      - name: config
        configMap:
          name: frigate-config-data
      - name: cache
        persistentVolumeClaim:
          claimName: frigate-cache
      - name: database
        persistentVolumeClaim:
          claimName: frigate-database
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  selector:
    app.kubernetes.io/name: frigate
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP